### ISSUE TITLE
Rename some fields, add field "student club" to paper list

### ISSUE THREAD

**Issue by JakubPrzystasz** [JakubPrzystasz/StronaProjektyKol#33]
- Show Students club name in papers list,reviews list  - add one common template for viewing single paper in list
- "gotowy do recenzji" instead of  "gotowy do oceny" - 'paper approved field'
- "streszczenie" instead of "opis" - paper field 'descirption'
- in add paper creation view add information about paper template
- "arytuły" instead of "referaty" (whole site)

**Comment by Smiercior** [comment]
Dobra co teraz dodałem:
- "streszczenie" instead of "opis" - paper field 'descirption'
- Show Students club name in papers list,reviews list
- "gotowy do recenzji" instead of "gotowy do oceny" - 'paper approved field'

**Comment by Smiercior** [comment]
OK all jest zrobione z wyjątkiem add one common template for viewing single paper in list

**Comment by Smiercior** [comment]
OK all jest zrobione z wyjątkiem add one common template for viewing single paper in list

**Comment by IMystyk** [comment]
If an issue was not fully completed please do not mark it as 'closed'.

**Comment by JakubPrzystasz** [comment]
Done
